### ISSUE TITLE
github: handle "bad credentials" error gracefully

### ISSUE THREAD

**Issue by pyokagan** [pyokagan/CanIHasReview#17]
The user may have revoked our access token (or it expired for whatever reason).

Currently we treat it like a fatal error, but we could handle it more gracefully by clearing the user session.

Example stacktrace:
```
StatusCodeError: 401 - {"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}
    at Request.plumbing.callback (/app/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/app/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.<anonymous> (/app/node_modules/request/request.js:1081:10)
    at Request.self.callback (/app/node_modules/request/request.js:186:22)
    at emitOne (events.js:96:13)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/app/node_modules/request/request.js:1001:12)
    at IncomingMessage.g (events.js:291:16)
    at IncomingMessage.emit (events.js:185:7)
    at emitNone (events.js:91:20)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by pyokagan** [comment]
Fixed in rewrite.
