### ISSUE TITLE
Bot did not post a new iteration for addressbook-level4#173

### ISSUE THREAD

**Issue by yamgent** [pyokagan/CanIHasReview#29]
I clicked the 'Submit New Iteration' in @CanIHasReview for https://github.com/se-edu/addressbook-level4/pull/273, but it did not post anything on my PR. Tried it a couple of times.

Works on my other PRs though.

**Comment by pyokagan** [comment]
@yamgent Thanks for the report. Interdiff generation is failing for some reason.

Relevant logs:
```
From https://github.com/se-edu/addressbook-level4
Note: checking out '941d0afebe52dc6bd86b60bd4a11861f48273900'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.
If you want to create a new branch to retain commits you create, you may

do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 941d0af... [#230] checkstyle: ensure consistent ordering of imports (#257)
[detached HEAD 2c8e8e6] Make DuplicatePersonException public
 Author: Tan Wang Leng <tanwangleng@outlook.com>
 1 file changed, 1 insertion(+), 1 deletion(-)
[detached HEAD 45cc33a] Add unit test for AddCommand
 Author: Tan Wang Leng <tanwangleng@outlook.com>
 1 file changed, 170 insertions(+)
error: could not apply 81b357c... Remove integrated test for AddCommand
 create mode 100644 src/test/java/seedu/address/logic/commands/AddCommandTest.java
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
Error: Command failed: git cherry-pick -X theirs 9321a79e2fc882fbfce56d31d2f8df32f11bd16c..81b357c9e6b04949f9f395c8529982e4905f7189
    at ChildProcess.<anonymous> (/app/lib/shell.js:52:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:192:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

I guess a hotfix would be to just continue on if interdiff generation fails, although I won't get bug reports if that happens though :-P

**Comment by pyokagan** [comment]
@yamgent Alright, I just pushed a fix. Hopefully it works now.
